-- Last updated: 8/20/2026, 1:58:17 AM
SELECT
CASE WHEN (N.A > C.B) THEN 'New York University'
WHEN (N.A < C.B) THEN 'California University'
ELSE 'No Winner'
END AS WINNER 
FROM
(SELECT COUNT(*) AS A FROM NEWYORK WHERE SCORE>=90) AS N,
(SELECT COUNT(*) AS B FROM CALIFORNIA WHERE SCORE>=90) AS C;