-- Last updated: 8/20/2026, 2:02:06 AM
SELECT
    SELL_DATE AS 'sell_date',
    COUNT(DISTINCT PRODUCT) AS 'num_sold',
    GROUP_CONCAT( DISTINCT PRODUCT 
                 ORDER BY PRODUCT) AS 'products'
FROM 
    ACTIVITIES
GROUP BY
    SELL_DATE
ORDER BY
    SELL_DATE;
    